name: locall_app
description: A new social media project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  permission_handler: ^11.2.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: any
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/core/common/env/
  fonts:
    - family: Josefin
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
    - family: Yeseva
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
dependency_overrides:
  intl: ^0.19.0
