// Mocks generated by Mockito 5.4.4 from annotations
// in locall_app/test/src/domain/usecases/location_status/watch_gps_status_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:locall_app/core/errors/failures.dart' as _i5;
import 'package:locall_app/src/domain/entities/location_status.dart' as _i6;
import 'package:locall_app/src/domain/repositories/location_status/location_status_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocationStatusRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationStatusRepo extends _i1.Mock
    implements _i2.LocationStatusRepo {
  MockLocationStatusRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.Failure, _i6.LocationStatus>> watchGpsStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchGpsStatus,
          [],
        ),
        returnValue:
            _i3.Stream<_i4.Either<_i5.Failure, _i6.LocationStatus>>.empty(),
      ) as _i3.Stream<_i4.Either<_i5.Failure, _i6.LocationStatus>>);
}
